### ISSUE TITLE
veye IMX327/IMX307对应的驱动可以做成动态加载的.ko文件吧？

### ISSUE THREAD

**Issue by mexbo** [veyeimaging/nvidia_jetson_veye_bsp#1]
这样就可以不用和内核一起编译，降低时间成本。

**Comment by leeyunhome** [comment]
Hello,

Failed to build from source.

I'm looking at the following two documents.
http://wiki.veye.cc/index.php/VEYE_CS_Camera_for_Jetson_TX2

http://wiki.veye.cc/index.php/VEYE_CS_Camera_source_for_Jetson

I am failing to build dts like this:
cd $L4T_DIR/sources/kernel/kernel-4.9/
make ARCH=arm64 O=$TEGRA_KERNEL_OUT dtbs

ps. Can the veye327 camera be used in the jetson nano production module in addition to the jetson nano devkit module (sdcard)?

Thank you.

**Comment by mmxuxp** [comment]
> 这样就可以不用和内核一起编译，降低时间成本。

我认为是可以的。 不过ko要有与内核完全一致的匹配度。我们暂时没有采取这种release的模式。

**Comment by mmxuxp** [comment]
> Hello,
> 
> Failed to build from source.
> 
> I'm looking at the following two documents.
> http://wiki.veye.cc/index.php/VEYE_CS_Camera_for_Jetson_TX2
> 
> http://wiki.veye.cc/index.php/VEYE_CS_Camera_source_for_Jetson
> 
> I am failing to build dts like this:
> cd $L4T_DIR/sources/kernel/kernel-4.9/
> make ARCH=arm64 O=$TEGRA_KERNEL_OUT dtbs
> 
> ps. Can the veye327 camera be used in the jetson nano production module in addition to the jetson nano devkit module (sdcard)?
> 
> Thank you.

Hi，
Sorry for reply so late. If you still have this problem, please visit forum.veye.cc to disucss details with me.
And of course this camera could be used on nano production module.

**Comment by mmxuxp** [comment]
Jetpack5.0 support modules now.
