### ISSUE TITLE
Miss kernel_csimx307veye327_config_32.4.2 file. 

### ISSUE THREAD

**Issue by 20chase** [veyeimaging/nvidia_jetson_veye_bsp#2]
Hi developers, 

I stuck at the `Build Kernel` step since I miss the `kernel_csimx307veye327_config_32.4.2` in `drivers_source`.  In this case, I am wondering is it possible to use `kernel_csimx307veye327_config_r32.3.1` for R32.4.2 version. Or, can you provide the missed file?

**Comment by mmxuxp** [comment]
hi，
sorry for missing this file. uploaded now.

**Comment by mmxuxp** [comment]
fixed
