### ISSUE TITLE
CS_IMX307  DBT update failed.

### ISSUE THREAD

**Issue by murphypei** [veyeimaging/nvidia_jetson_veye_bsp#3]
Hi, I have updated image、ko and dbt files through prebuilt binaries as the [wiki](http://wiki.veye.cc/index.php/VEYE_CS_Camera_for_Jetson_TX2#XAVIER_NX_Devkit). After all the done, I checked if the update was successful:
 
I can find the csx307 of the output of `ls /sys/bus/i2c/drivers/`, but there is no any "307" of the output of `ls /proc/device-tree/cam_i2cmux/i2c@*`.

My board is Xavier NX and the system is Jetpack 5.0.2, I have double checked the dbt files and extlinux.conf. Could you give any suggestions?

**Comment by mmxuxp** [comment]
Hi，Please post your question on forum.veye.cc
Thanks!
