### ISSUE TITLE
使用v4l2读取相机时使用图像尺寸2464x2056（v4l2反馈的标准尺寸）出现重影现象。

### ISSUE THREAD

**Issue by ggww1133** [veyeimaging/nvidia_jetson_veye_bsp#4]
使用v4l2gray_mvcam_jetson工具时出现反馈信息

![图片1](https://user-images.githubusercontent.com/43953496/232416374-09dd87aa-24b7-42df-b23c-b51279735968.png)

之后将v4l2代码中尺寸设置为2496x2056时图像正常显示。之后再次测试重启设备后直接捕获2496x2056的图像出现错行读取数据长度为5065984（2464x2056）,再次调用v4l2gray_mvcam_jetson后，运行v4l2代码捕获图像正常。长度为

![图片2](https://user-images.githubusercontent.com/43953496/232416553-81c400ac-4de0-4f1a-a762-8f04d5712c06.png)

期望：能够正常运行v4l2代码捕获2496x2056尺寸图像。

**Comment by mmxuxp** [comment]
推测你使用的是MV-MIPI-IMX264M。
这个模组最大分辨率就是2464×2056，传感器就不支持2496这个宽度。
之所以有2496这个数，是jetson平台做的行buffer的对齐操作。简单点说，现在摄像头输出2464像素/行，jetson会给2496 bytes的buffer来存一行。 目的是为了硬件加速操作方便。
另外，如以后有问题麻烦提交到forum.veye.cc,论坛上的响应速度更快。
